/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ie.gmit.woman2woman;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int background=0x7f040000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
        public static final int paddingT=0x7f050003;
        public static final int txtSize=0x7f050002;
    }
    public static final class drawable {
        public static final int breastchck=0x7f020000;
        public static final int depression=0x7f020001;
        public static final int freeheart=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int measuring=0x7f020004;
        public static final int menopause=0x7f020005;
        public static final int pregnancy=0x7f020006;
        public static final int selfexam=0x7f020007;
        public static final int violence=0x7f020008;
        public static final int weight=0x7f020009;
    }
    public static final class id {
        public static final int BodyFatDisplay=0x7f080020;
        public static final int ButtonBMI=0x7f080005;
        public static final int ButtonBodyFat=0x7f08000b;
        public static final int ButtonHip=0x7f08000e;
        public static final int ButtonHow=0x7f080011;
        public static final int ButtonLean=0x7f080008;
        public static final int Name=0x7f080002;
        public static final int age=0x7f08000a;
        public static final int breastChckLayout=0x7f080013;
        public static final int buttonNoPregnancy=0x7f08001e;
        public static final int buttonPregnancy=0x7f08001f;
        public static final int containerTable=0x7f080000;
        public static final int height=0x7f080007;
        public static final int hips=0x7f080010;
        public static final int imageBreastchck=0x7f08001a;
        public static final int imageButtonBodyMetrics=0x7f080017;
        public static final int imageButtonDepression=0x7f080019;
        public static final int imageButtonMenopause=0x7f080018;
        public static final int imageButtonPregnancy=0x7f08001c;
        public static final int imageButtonViolence=0x7f08001b;
        public static final int imageViewMeasure=0x7f080014;
        public static final int myTextView=0x7f080015;
        public static final int tableRow1=0x7f080001;
        public static final int tableRow2=0x7f080003;
        public static final int tableRow3=0x7f080006;
        public static final int tableRow4=0x7f080009;
        public static final int tableRow5=0x7f08000c;
        public static final int tableRow6=0x7f08000f;
        public static final int tableRow7=0x7f080012;
        public static final int textViewDep=0x7f080016;
        public static final int textViewPregnancy=0x7f08001d;
        public static final int waist=0x7f08000d;
        public static final int weight=0x7f080004;
    }
    public static final class layout {
        public static final int activity_body_metrics=0x7f030000;
        public static final int activity_breast_check=0x7f030001;
        public static final int activity_depression=0x7f030002;
        public static final int activity_how=0x7f030003;
        public static final int activity_main=0x7f030004;
        public static final int activity_menopause=0x7f030005;
        public static final int activity_pregnancy=0x7f030006;
        public static final int activity_text_display=0x7f030007;
    }
    public static final class string {
        public static final int Age=0x7f060027;
        public static final int BMI=0x7f060010;
        public static final int BodyFat=0x7f060011;
        public static final int BodyFatDisplay=0x7f060021;
        public static final int Btn1=0x7f060002;
        public static final int Btn2=0x7f060003;
        public static final int Btn3=0x7f060004;
        public static final int Btn4=0x7f060005;
        public static final int Btn5=0x7f060006;
        public static final int Btn6=0x7f060007;
        public static final int Height=0x7f060026;
        public static final int Hip=0x7f060020;
        public static final int Hip2=0x7f060029;
        public static final int Hip_Waist=0x7f06000f;
        public static final int How=0x7f06002a;
        public static final int Lean_Body_Mass=0x7f060012;
        public static final int Map_label=0x7f060008;
        public static final int Name=0x7f060024;
        public static final int Pregnancy=0x7f060022;
        public static final int Waist=0x7f060028;
        public static final int Weight=0x7f060025;
        public static final int action_settings=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int bMet=0x7f060019;
        public static final int check=0x7f060015;
        public static final int dep=0x7f060013;
        public static final int hello_world=0x7f06001c;
        public static final int meno=0x7f060014;
        public static final int notPregnancy=0x7f060023;
        public static final int preg=0x7f060017;
        public static final int quit=0x7f06000d;
        public static final int results=0x7f06000c;
        public static final int search=0x7f06000b;
        public static final int showAll=0x7f06000a;
        public static final int title_activity_body_metrics=0x7f06000e;
        public static final int title_activity_breast_check=0x7f06001a;
        public static final int title_activity_depression=0x7f06001b;
        public static final int title_activity_map=0x7f060009;
        public static final int title_activity_menopause=0x7f06001e;
        public static final int title_activity_pregnancy=0x7f06001d;
        public static final int title_activity_text_display=0x7f06001f;
        public static final int urDetails=0x7f060018;
        public static final int viol=0x7f060016;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
